version: '3.8'

services:
  estudiantes-service:
    image: openjdk:17-jdk-slim
    container_name: estudiantes-service
    build:
      context: ./be-estudiantes
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/estudiantes_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - estudiantes-db

  estudiantes-db:
    image: postgres:15
    container_name: estudiantes-db
    environment:
      POSTGRES_DB: estudiantes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - estudiantes_data:/var/lib/postgresql/data

  carreras-service:
    image: openjdk:17-jdk-slim
    container_name: carreras-service
    build:
      context: ./be-carreras
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/carreras_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - ESTUDIANTES_SERVICE_URL=http://localhost:8080/api/estudiantes  # URL del microservicio de estudiantes
    depends_on:
      - carreras-db
      - estudiantes-service

  carreras-db:
    image: postgres:15
    container_name: carreras-db
    environment:
      POSTGRES_DB: carreras_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - carreras_data:/var/lib/postgresql/data

volumes:
  estudiantes_data:
  carreras_data:
